import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900`}>
      {/* Header global - ancho completo */}
      <header className="bg-white shadow-md w-full">
        <div className="max-w-7xl mx-auto flex items-center px-6 py-6">
          <Image
            src="/resources/LOGO.png"
            alt="Logo ECIbienestar"
            width={64}
            height={64}
          />
          <h1 className="ml-4 text-3xl font-bold text-gray-900">
            ECIbienestar - Gestión de Préstamos Deportivos
          </h1>
        </div>
      </header>

      {/* Contenido principal */}
      {children}
    </div>
  );
}
